// The online build: `node tools/pages.mjs <out>` writes the static site GitHub
// Pages serves. The same files the Portal serves (toolkit-app.json's include
// list), plus what an iPhone needs to keep Flow as a home-screen app: a web
// manifest, icons, and a service worker that precaches every file so it opens
// offline. Records stay in the browser (IndexedDB) until Sync is set up.
import { readFileSync, writeFileSync, mkdirSync, cpSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const out = process.argv[2];
if (!out) throw new Error('usage: node tools/pages.mjs <out-dir>');
const app = JSON.parse(readFileSync(join(root, 'toolkit-app.json'), 'utf8'));

const walk = (dir) => readdirSync(dir).flatMap((f) => (statSync(join(dir, f)).isDirectory() ? walk(join(dir, f)) : [join(dir, f)]));
const skip = (f) => /\.test\.|(^|\/)\.|\.md$/.test(f);
const copy = (rel) => { const to = join(out, rel); mkdirSync(dirname(to), { recursive: true }); cpSync(join(root, rel), to); };

mkdirSync(out, { recursive: true });
for (const pattern of [...app.static.include, 'icons/**']) {
  if (pattern.endsWith('/**')) {
    const dir = join(root, pattern.slice(0, -3));
    if (existsSync(dir)) for (const f of walk(dir)) { const rel = relative(root, f); if (!skip(rel)) copy(rel); }
  } else copy(pattern);
}

writeFileSync(join(out, 'manifest.webmanifest'), JSON.stringify({
  name: app.name, short_name: app.pwa?.shortName || app.name, start_url: './', scope: './',
  display: 'standalone', background_color: '#1b2340', theme_color: '#1b2340',
  icons: [192, 512].map((s) => ({ src: `icons/icon-${s}.png`, sizes: `${s}x${s}`, type: 'image/png', purpose: 'any' })),
}, null, 2));

const head = [
  '<link rel="manifest" href="manifest.webmanifest">',
  '<meta name="apple-mobile-web-app-capable" content="yes">',
  '<meta name="mobile-web-app-capable" content="yes">',
  '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">',
  `<meta name="apple-mobile-web-app-title" content="${app.name}">`,
  '<link rel="apple-touch-icon" href="icons/icon-180.png">',
  "<script>if ('serviceWorker' in navigator) addEventListener('load', () => navigator.serviceWorker.register('sw.js'));</script>",
].join('\n');
const index = join(out, 'index.html');
writeFileSync(index, readFileSync(index, 'utf8').replace('</head>', `${head}\n</head>`));

// Precache everything, versioned by the files' contents so a new deploy replaces the cache.
const files = walk(out).map((f) => relative(out, f)).sort();
let hash = 0;
for (const f of files) for (const b of readFileSync(join(out, f))) hash = (hash * 31 + b) >>> 0;
writeFileSync(join(out, 'sw.js'), `// Generated by tools/pages.mjs: precaches the app so it opens offline.
const CACHE = 'flow-${hash.toString(36)}';
const FILES = ${JSON.stringify(['./', ...files.map((f) => './' + f)], null, 1)};
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES))); self.skipWaiting(); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))); self.clients.claim(); });
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)));
});
`);
console.log(`${files.length + 1} files → ${out}`);
